"""add_factor_and_risk_models

Revision ID: 623b024262a0
Revises:
Create Date: 2025-12-01 22:02:18.901432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "623b024262a0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "covariance_matrices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("universe_hash", sa.String(), nullable=False),
        sa.Column("matrix_blob", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_covariance_matrices_as_of_date"),
        "covariance_matrices",
        ["as_of_date"],
        unique=False,
    )
    op.create_index(
        "ix_covariance_matrices_as_of_date_universe_hash",
        "covariance_matrices",
        ["as_of_date", "universe_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_covariance_matrices_id"),
        "covariance_matrices",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_covariance_matrices_universe_hash"),
        "covariance_matrices",
        ["universe_hash"],
        unique=False,
    )
    op.create_table(
        "factor_exposures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("quality", sa.Float(), nullable=True),
        sa.Column("momentum", sa.Float(), nullable=True),
        sa.Column("low_vol", sa.Float(), nullable=True),
        sa.Column("size", sa.Float(), nullable=True),
        sa.Column("composite_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_factor_exposures_as_of_date"),
        "factor_exposures",
        ["as_of_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_exposures_id"),
        "factor_exposures",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_exposures_symbol"),
        "factor_exposures",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        "ix_factor_exposures_symbol_as_of_date",
        "factor_exposures",
        ["symbol", "as_of_date"],
        unique=False,
    )
    op.create_table(
        "fundamentals_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("pe", sa.Float(), nullable=True),
        sa.Column("pb", sa.Float(), nullable=True),
        sa.Column("ps", sa.Float(), nullable=True),
        sa.Column("roe", sa.Float(), nullable=True),
        sa.Column("roce", sa.Float(), nullable=True),
        sa.Column("debt_to_equity", sa.Float(), nullable=True),
        sa.Column("sales_growth_yoy", sa.Float(), nullable=True),
        sa.Column("profit_growth_yoy", sa.Float(), nullable=True),
        sa.Column("eps_growth_3y", sa.Float(), nullable=True),
        sa.Column("operating_margin", sa.Float(), nullable=True),
        sa.Column("net_margin", sa.Float(), nullable=True),
        sa.Column("interest_coverage", sa.Float(), nullable=True),
        sa.Column("promoter_holding", sa.Float(), nullable=True),
        sa.Column("fii_holding", sa.Float(), nullable=True),
        sa.Column("dii_holding", sa.Float(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fundamentals_snapshot_as_of_date"),
        "fundamentals_snapshot",
        ["as_of_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fundamentals_snapshot_id"),
        "fundamentals_snapshot",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fundamentals_snapshot_symbol"),
        "fundamentals_snapshot",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        "ix_fundamentals_snapshot_symbol_as_of_date",
        "fundamentals_snapshot",
        ["symbol", "as_of_date"],
        unique=False,
    )
    op.create_table(
        "risk_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("volatility", sa.Float(), nullable=True),
        sa.Column("beta", sa.Float(), nullable=True),
        sa.Column("tail_beta", sa.Float(), nullable=True),
        sa.Column("skew", sa.Float(), nullable=True),
        sa.Column("kurtosis", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_model_as_of_date"),
        "risk_model",
        ["as_of_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_model_id"),
        "risk_model",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_model_symbol"),
        "risk_model",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        "ix_risk_model_symbol_as_of_date",
        "risk_model",
        ["symbol", "as_of_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_risk_model_symbol_as_of_date", table_name="risk_model")
    op.drop_index(op.f("ix_risk_model_symbol"), table_name="risk_model")
    op.drop_index(op.f("ix_risk_model_id"), table_name="risk_model")
    op.drop_index(op.f("ix_risk_model_as_of_date"), table_name="risk_model")
    op.drop_table("risk_model")
    op.drop_index(
        "ix_fundamentals_snapshot_symbol_as_of_date",
        table_name="fundamentals_snapshot",
    )
    op.drop_index(
        op.f("ix_fundamentals_snapshot_symbol"),
        table_name="fundamentals_snapshot",
    )
    op.drop_index(
        op.f("ix_fundamentals_snapshot_id"),
        table_name="fundamentals_snapshot",
    )
    op.drop_index(
        op.f("ix_fundamentals_snapshot_as_of_date"),
        table_name="fundamentals_snapshot",
    )
    op.drop_table("fundamentals_snapshot")
    op.drop_index(
        "ix_factor_exposures_symbol_as_of_date",
        table_name="factor_exposures",
    )
    op.drop_index(op.f("ix_factor_exposures_symbol"), table_name="factor_exposures")
    op.drop_index(op.f("ix_factor_exposures_id"), table_name="factor_exposures")
    op.drop_index(op.f("ix_factor_exposures_as_of_date"), table_name="factor_exposures")
    op.drop_table("factor_exposures")
    op.drop_index(
        op.f("ix_covariance_matrices_universe_hash"),
        table_name="covariance_matrices",
    )
    op.drop_index(
        op.f("ix_covariance_matrices_id"),
        table_name="covariance_matrices",
    )
    op.drop_index(
        "ix_covariance_matrices_as_of_date_universe_hash",
        table_name="covariance_matrices",
    )
    op.drop_index(
        op.f("ix_covariance_matrices_as_of_date"),
        table_name="covariance_matrices",
    )
    op.drop_table("covariance_matrices")
    # ### end Alembic commands ###
