"""add_portfolio_constraints_and_weights

Revision ID: 6cbb88907479
Revises: 623b024262a0
Create Date: 2025-12-02 00:11:45.585623

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6cbb88907479"
down_revision: Union[str, None] = "623b024262a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
